### PR TITLE
Prefer static keyword over unnamed namespaces

### PR DESCRIPTION
**Pull request by lava**

### CODE REVIEW

**Comment by dominiklohmann** [comment]
I think an argument can be made to keep using anonymous namespaces for both, but minimizing the scope of them. The tradeoff to make here is between using less vertical space and having a unified way of keeping things local to a translation unit.

Note that there was a plan to deprecate this use of the static keyword, but it that decision was reversed late in the process of creating C++11.

**Comment by mavam** [comment]
For a while, anonymous namespaces were the preferred way to handle internal linkage. See [this SO post](https://stackoverflow.com/questions/154469/unnamed-anonymous-namespaces-vs-static-functions) for details. But as @dominiklohmann pointed out, [this has been reversed](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1012).

I have no strong opinion on how to handle this situation, as long is it is consistent. So far we use anonymous namespaces. If we switch, we wind up with two different methods to do the same thing unless we refactor all occurrences. Do you think the refactoring is worth the benefit?

**Comment by lava** [comment]
It's not a huge refactoring either way: I'm currently counting 17 functions and 0 variables in `vast` and `vast-pro` combined that would need to be changed, I'm happy to create a PR with the update.

I also don't mind creating PR where the anonymous are re-redeclared around every entity, but I have to admit that it looks a bit odd/unusual:
```
namespace {

int x;

} // namespace

namespace {

int y;

} // namespace
```
whereas use of `static` is a bit more common since its used everywhere in the C world.

**Comment by mavam** [comment]
Seems like a manageable operation. Feel free to proceed! ✅

**Review by dominiklohmann — APPROVED** [review]

**Comment by dominiklohmann** [comment]
@lava is this still a thing you want to pursue?

**Comment by lava** [comment]
@dominiklohmann Yes, this got a bit stalled because the clang-query I had constructed is only on my machine in the office, but I'd like to resume this when quarantine is over.

**Comment by dominiklohmann** [comment]
I am closing this due to inactivity. All new code we've written in the meantime has used anonymous namespaces. There exists no traction behind this proposal.

**Pull request closed without merging**
